
/*
Encapsulation means to protect, to hide inner working of class to be accessed from outside. For that purpose,
we use getters and setters. Getters and Setters are implicit, they automatically generated, but you can override
them.
 */

class User(firstName: String = "First Name", var lastName: String = "Last Name", var age: Int = 0) {

    // late initialization means we will initialize it later
    // it will work with only classes not primitive types like Int
    lateinit var favouriteMovie: String

    var firstName = firstName

        /*
        These are the implicit getters and setters that are automatically generated by kotlin,
        but you can override them
        get() {
            return field
        }

        set(){
            field = value
        }
        */
        get(){
            return "First Name: $field."
        }
        set(value){
            println("$value was assigned to firstname property.")
            field = value
        }
}

fun main(){
    var user = User("Alex", "smith", 24)

    user.firstName = "John"

    // observe the output
    println(user.firstName)
    println(user.lastName)
    println(user.age)
}


/*

class User(firstName: String = "First Name",
           lastName: String = "Last Name",
           age: Int = 0) {

    var firstName = firstName
        get() {
            return "First Name: $field"
        }
        set(value) {
            println("$value was assigned to firstName property.")
            field = value
        }

    var lastName = lastName
        get() {
            return "Last Name: $field"
        }
        set(value) {
            println("$value was assigned to lastName property.")
            field = value
        }

    var age = age
        get() {
            return field // For age, just return the number directly
        }
        set(value) {
            if (value >= 0) { // simple validation
                println("$value was assigned to age property.")
                field = value
            } else {
                println("Age cannot be negative.")
            }
        }
}
 */